-- Start of /home/bismuth/git/chase/dist-newstyle/build/x86_64-linux/ghc-9.10.3/chase-0.1.0.0/x/chase/build/chase/autogen/Paths_chase.hs
{-# LANGUAGE CPP #-}
{-# LANGUAGE NoRebindableSyntax #-}
#if __GLASGOW_HASKELL__ >= 810
{-# OPTIONS_GHC -Wno-prepositive-qualified-module #-}
#endif
{-# OPTIONS_GHC -Wno-missing-import-lists #-}
{-# OPTIONS_GHC -w #-}

{-|
Module      : Paths_chase
Description : Data file location, and package version and installation
              directories.

WARNING: This module was generated by Cabal. Any modifications will be
overwritten if the module is regenerated.

This module exports a function to locate data files, and values that record
the version of the package and some directories which the package has been
configured to be installed into.

For further information about Cabal's options for its configuration step, and
their default values, see the Cabal User Guide.
-}

module Paths_chase (
    version,
    getBinDir, getLibDir, getDynLibDir, getDataDir, getLibexecDir,
    getDataFileName, getSysconfDir
  ) where


import qualified Control.Exception as Exception
import Data.Version (Version(..))
import System.Environment (getEnv)
import Prelude


#if defined(VERSION_base)

#if MIN_VERSION_base(4,0,0)
catchIO :: IO a -> (Exception.IOException -> IO a) -> IO a
#else
catchIO :: IO a -> (Exception.Exception -> IO a) -> IO a
#endif

#else
catchIO :: IO a -> (Exception.IOException -> IO a) -> IO a
#endif
catchIO = Exception.catch

-- |The package version.
version :: Version
version = Version [0,1,0,0] []

-- |If the argument is a filename, the result is the name of a corresponding
-- file on the system on which the program is running, if the file were listed
-- in the @data-files@ field of the package's Cabal package description file.
-- No check is performed that the given filename is listed in that field.
getDataFileName :: FilePath -> IO FilePath
getDataFileName name = do
  dir <- getDataDir
  return (dir `joinFileName` name)

-- |The location of the directory specified by Cabal's @--bindir@ option (where
-- executables that the user might invoke are installed). This can be overridden
-- at runtime using the environment variable chase_bindir.
getBinDir :: IO FilePath

-- |The location of the directory specified by Cabal's @--libdir@ option (where
-- object libraries are installed). This can be overridden at runtime using the
-- environment variable chase_libdir.
getLibDir :: IO FilePath

-- |The location of the directory specified by Cabal's @--dynlibdir@ option
-- (where dynamic libraries are installed). This can be overridden at runtime
-- using the environment variable chase_dynlibdir.
getDynLibDir :: IO FilePath

-- |The location of the directory specified by Cabal's @--datadir@ option (where
-- architecture-independent data files are installed). This can be overridden at
-- runtime using the environment variable chase_datadir.
getDataDir :: IO FilePath

-- |The location of the directory specified by Cabal's @--libexedir@ option
-- (where executables that are not expected to be invoked directly by the user
-- are installed). This can be overridden at runtime using the environment
-- variable chase_libexedir.
getLibexecDir :: IO FilePath

-- |The location of the directory specified by Cabal's @--sysconfdir@ option
-- (where configuration files are installed). This can be overridden at runtime
-- using the environment variable chase_sysconfdir.
getSysconfDir :: IO FilePath




bindir, libdir, dynlibdir, datadir, libexecdir, sysconfdir :: FilePath
bindir     = "/home/bismuth/.cabal/bin"
libdir     = "/home/bismuth/.cabal/lib/x86_64-linux-ghc-9.10.3-c0c3/chase-0.1.0.0-inplace-chase"
dynlibdir  = "/home/bismuth/.cabal/lib/x86_64-linux-ghc-9.10.3-c0c3"
datadir    = "/home/bismuth/.cabal/share/x86_64-linux-ghc-9.10.3-c0c3/chase-0.1.0.0"
libexecdir = "/home/bismuth/.cabal/libexec/x86_64-linux-ghc-9.10.3-c0c3/chase-0.1.0.0"
sysconfdir = "/home/bismuth/.cabal/etc"

getBinDir     = catchIO (getEnv "chase_bindir")     (\_ -> return bindir)
getLibDir     = catchIO (getEnv "chase_libdir")     (\_ -> return libdir)
getDynLibDir  = catchIO (getEnv "chase_dynlibdir")  (\_ -> return dynlibdir)
getDataDir    = catchIO (getEnv "chase_datadir")    (\_ -> return datadir)
getLibexecDir = catchIO (getEnv "chase_libexecdir") (\_ -> return libexecdir)
getSysconfDir = catchIO (getEnv "chase_sysconfdir") (\_ -> return sysconfdir)



joinFileName :: String -> String -> FilePath
joinFileName ""  fname = fname
joinFileName "." fname = fname
joinFileName dir ""    = dir
joinFileName dir@(c:cs) fname
  | isPathSeparator (lastChar c cs) = dir ++ fname
  | otherwise                       = dir ++ pathSeparator : fname
 where
  -- We do not use Data.List.NonEmpty.last, as that would limit the module to
  -- base >= 4.9.0.0 (GHC >= 8.0.1).
  lastChar x [] = x
  lastChar _ (x:xs) = lastChar x xs

pathSeparator :: Char
pathSeparator = '/'

isPathSeparator :: Char -> Bool
isPathSeparator c = c == '/'
-- End of /home/bismuth/git/chase/dist-newstyle/build/x86_64-linux/ghc-9.10.3/chase-0.1.0.0/x/chase/build/chase/autogen/Paths_chase.hs

-- Start of /home/bismuth/git/chase/dist-newstyle/build/x86_64-linux/ghc-9.10.3/chase-0.1.0.0/x/chase/build/chase/autogen/PackageInfo_chase.hs
{-# LANGUAGE NoRebindableSyntax #-}
{-# OPTIONS_GHC -Wno-missing-import-lists #-}
{-# OPTIONS_GHC -w #-}

{-|
Module      : PackageInfo_chase
Description : Contents of some of the package's Cabal file's fields.

WARNING: This module was generated by Cabal. Any modifications will be
overwritten if the module is regenerated.

This module exports values that record information from some of the fields of
the package's Cabal package description file (Cabal file).

For further information about the fields in a Cabal file, see the Cabal User
Guide.
-}

module PackageInfo_chase (
    name,
    version,
    synopsis,
    copyright,
    homepage,
  ) where

import Data.Version (Version(..))
import Prelude

-- |The content of the @name@ field of the package's Cabal file, but with any
-- hyphen characters replaced by underscore characters.
name :: String
name = "chase"
-- |The content of the @version@ field of the package's Cabal file.
version :: Version
version = Version [0,1,0,0] []

-- |The content of the @synopsis@ field of the package's Cabal file.
synopsis :: String
synopsis = "Structural compression of Haskell source for LLM context"
-- |The content of the @copyright@ field of the package's Cabal file.
copyright :: String
copyright = ""
-- |The content of the @homepage@ field of the package's Cabal file.
homepage :: String
homepage = ""
-- End of /home/bismuth/git/chase/dist-newstyle/build/x86_64-linux/ghc-9.10.3/chase-0.1.0.0/x/chase/build/chase/autogen/PackageInfo_chase.hs

-- Start of /home/bismuth/git/chase/dist-newstyle/build/x86_64-linux/ghc-9.10.3/chase-0.1.0.0/build/autogen/Paths_chase.hs
{-# LANGUAGE CPP #-}
{-# LANGUAGE NoRebindableSyntax #-}
#if __GLASGOW_HASKELL__ >= 810
{-# OPTIONS_GHC -Wno-prepositive-qualified-module #-}
#endif
{-# OPTIONS_GHC -Wno-missing-import-lists #-}
{-# OPTIONS_GHC -w #-}

{-|
Module      : Paths_chase
Description : Data file location, and package version and installation
              directories.

WARNING: This module was generated by Cabal. Any modifications will be
overwritten if the module is regenerated.

This module exports a function to locate data files, and values that record
the version of the package and some directories which the package has been
configured to be installed into.

For further information about Cabal's options for its configuration step, and
their default values, see the Cabal User Guide.
-}

module Paths_chase (
    version,
    getBinDir, getLibDir, getDynLibDir, getDataDir, getLibexecDir,
    getDataFileName, getSysconfDir
  ) where


import qualified Control.Exception as Exception
import Data.Version (Version(..))
import System.Environment (getEnv)
import Prelude


#if defined(VERSION_base)

#if MIN_VERSION_base(4,0,0)
catchIO :: IO a -> (Exception.IOException -> IO a) -> IO a
#else
catchIO :: IO a -> (Exception.Exception -> IO a) -> IO a
#endif

#else
catchIO :: IO a -> (Exception.IOException -> IO a) -> IO a
#endif
catchIO = Exception.catch

-- |The package version.
version :: Version
version = Version [0,1,0,0] []

-- |If the argument is a filename, the result is the name of a corresponding
-- file on the system on which the program is running, if the file were listed
-- in the @data-files@ field of the package's Cabal package description file.
-- No check is performed that the given filename is listed in that field.
getDataFileName :: FilePath -> IO FilePath
getDataFileName name = do
  dir <- getDataDir
  return (dir `joinFileName` name)

-- |The location of the directory specified by Cabal's @--bindir@ option (where
-- executables that the user might invoke are installed). This can be overridden
-- at runtime using the environment variable chase_bindir.
getBinDir :: IO FilePath

-- |The location of the directory specified by Cabal's @--libdir@ option (where
-- object libraries are installed). This can be overridden at runtime using the
-- environment variable chase_libdir.
getLibDir :: IO FilePath

-- |The location of the directory specified by Cabal's @--dynlibdir@ option
-- (where dynamic libraries are installed). This can be overridden at runtime
-- using the environment variable chase_dynlibdir.
getDynLibDir :: IO FilePath

-- |The location of the directory specified by Cabal's @--datadir@ option (where
-- architecture-independent data files are installed). This can be overridden at
-- runtime using the environment variable chase_datadir.
getDataDir :: IO FilePath

-- |The location of the directory specified by Cabal's @--libexedir@ option
-- (where executables that are not expected to be invoked directly by the user
-- are installed). This can be overridden at runtime using the environment
-- variable chase_libexedir.
getLibexecDir :: IO FilePath

-- |The location of the directory specified by Cabal's @--sysconfdir@ option
-- (where configuration files are installed). This can be overridden at runtime
-- using the environment variable chase_sysconfdir.
getSysconfDir :: IO FilePath




bindir, libdir, dynlibdir, datadir, libexecdir, sysconfdir :: FilePath
bindir     = "/home/bismuth/.cabal/bin"
libdir     = "/home/bismuth/.cabal/lib/x86_64-linux-ghc-9.10.3-c0c3/chase-0.1.0.0-inplace"
dynlibdir  = "/home/bismuth/.cabal/lib/x86_64-linux-ghc-9.10.3-c0c3"
datadir    = "/home/bismuth/.cabal/share/x86_64-linux-ghc-9.10.3-c0c3/chase-0.1.0.0"
libexecdir = "/home/bismuth/.cabal/libexec/x86_64-linux-ghc-9.10.3-c0c3/chase-0.1.0.0"
sysconfdir = "/home/bismuth/.cabal/etc"

getBinDir     = catchIO (getEnv "chase_bindir")     (\_ -> return bindir)
getLibDir     = catchIO (getEnv "chase_libdir")     (\_ -> return libdir)
getDynLibDir  = catchIO (getEnv "chase_dynlibdir")  (\_ -> return dynlibdir)
getDataDir    = catchIO (getEnv "chase_datadir")    (\_ -> return datadir)
getLibexecDir = catchIO (getEnv "chase_libexecdir") (\_ -> return libexecdir)
getSysconfDir = catchIO (getEnv "chase_sysconfdir") (\_ -> return sysconfdir)



joinFileName :: String -> String -> FilePath
joinFileName ""  fname = fname
joinFileName "." fname = fname
joinFileName dir ""    = dir
joinFileName dir@(c:cs) fname
  | isPathSeparator (lastChar c cs) = dir ++ fname
  | otherwise                       = dir ++ pathSeparator : fname
 where
  -- We do not use Data.List.NonEmpty.last, as that would limit the module to
  -- base >= 4.9.0.0 (GHC >= 8.0.1).
  lastChar x [] = x
  lastChar _ (x:xs) = lastChar x xs

pathSeparator :: Char
pathSeparator = '/'

isPathSeparator :: Char -> Bool
isPathSeparator c = c == '/'
-- End of /home/bismuth/git/chase/dist-newstyle/build/x86_64-linux/ghc-9.10.3/chase-0.1.0.0/build/autogen/Paths_chase.hs

-- Start of /home/bismuth/git/chase/dist-newstyle/build/x86_64-linux/ghc-9.10.3/chase-0.1.0.0/build/autogen/PackageInfo_chase.hs
{-# LANGUAGE NoRebindableSyntax #-}
{-# OPTIONS_GHC -Wno-missing-import-lists #-}
{-# OPTIONS_GHC -w #-}

{-|
Module      : PackageInfo_chase
Description : Contents of some of the package's Cabal file's fields.

WARNING: This module was generated by Cabal. Any modifications will be
overwritten if the module is regenerated.

This module exports values that record information from some of the fields of
the package's Cabal package description file (Cabal file).

For further information about the fields in a Cabal file, see the Cabal User
Guide.
-}

module PackageInfo_chase (
    name,
    version,
    synopsis,
    copyright,
    homepage,
  ) where

import Data.Version (Version(..))
import Prelude

-- |The content of the @name@ field of the package's Cabal file, but with any
-- hyphen characters replaced by underscore characters.
name :: String
name = "chase"
-- |The content of the @version@ field of the package's Cabal file.
version :: Version
version = Version [0,1,0,0] []

-- |The content of the @synopsis@ field of the package's Cabal file.
synopsis :: String
synopsis = "Structural compression of Haskell source for LLM context"
-- |The content of the @copyright@ field of the package's Cabal file.
copyright :: String
copyright = ""
-- |The content of the @homepage@ field of the package's Cabal file.
homepage :: String
homepage = ""
-- End of /home/bismuth/git/chase/dist-newstyle/build/x86_64-linux/ghc-9.10.3/chase-0.1.0.0/build/autogen/PackageInfo_chase.hs

-- Start of /home/bismuth/git/chase/src/Chase.hs
module Chase
  ( -- * Types
    module Chase.Types
    -- * Pipeline
  , module Chase.Pipeline
    -- * JSON annotations loader
  , module Chase.Annotations.Json
    -- * Rendering (re-exported for testing)
  , renderChaseFile
  ) where

import Chase.Types
import Chase.Pipeline
import Chase.Annotations.Json
import Chase.Render (renderChaseFile)-- End of /home/bismuth/git/chase/src/Chase.hs

-- Start of /home/bismuth/git/chase/src/Chase/Render.hs
module Chase.Render
  ( renderChaseFile
  ) where

import qualified Data.Text as T
import Data.Text (Text)

import Chase.Types

renderChaseFile :: ChaseFile -> Text
renderChaseFile ChaseFile{..} = T.unlines $
     header
  <> renderExtensions chaseExtensions
  <> renderFixities   chaseFixities
  <> renderImports    chaseImports
  <> renderConstants  chaseConstants
  <> renderTopologies chaseTopologies
  <> renderDataDecls  chaseDataDecls
  <> renderPatternsWithInvariants chasePatterns chaseInvariants
  <> renderSignaturesWithInvariants chaseSignatures chaseInvariants
  <> renderDecisions  chaseDecisions
  <> renderParseErrors chaseParseErrors
  where
    header =
      [ "%file " <> T.pack chaseSourcePath
      , "%mod "  <> chaseModuleName
      , ""
      ]

renderExtensions :: [Text] -> [Text]
renderExtensions [] = []
renderExtensions xs = ["%ext " <> T.intercalate ", " xs, ""]

-- | Fixity block. One line per fixity declaration, verbatim, indented
-- under a %fixity heading. Placed right after %ext because it is
-- meta-context — it tells the reader how operator-using code parses.
renderFixities :: [Fixity] -> [Text]
renderFixities [] = []
renderFixities fs = "%fixity" : map (("  " <>) . fixVerbatim) fs <> [""]

renderImports :: [Text] -> [Text]
renderImports [] = []
renderImports imps =
  let collapsed = filter (not . T.null) (map collapseImport imps)
  in [ "%uses " <> i | i <- collapsed ] <> [""]

collapseImport :: Text -> Text
collapseImport raw =
  let oneLine  = T.unwords (T.words raw)
      chopped  = T.takeWhile (/= '(') oneLine
      stripped = T.strip chopped
  in case T.stripPrefix "import " stripped of
       Just rest -> T.strip rest
       Nothing   -> stripped

renderConstants :: [Constant] -> [Text]
renderConstants [] = []
renderConstants cs = map renderOne cs <> [""]
  where
    renderOne Constant{..} =
      let suffix = case constNotes of
            [] -> ""
            ns -> "  -- " <> T.intercalate "; " (map renderNote ns)
      in "%const " <> constName <> " = " <> constValueDoc <> suffix
    renderNote (Note t)    = t
    renderNote (BugNote t) = "BUG: " <> t

renderTopologies :: [Topology] -> [Text]
renderTopologies [] = []
renderTopologies tops = concatMap renderOne tops <> [""]
  where
    renderOne Topology{..} =
      ( "%machine " <> topName
        <> " vertices=" <> T.intercalate "," topVertices )
      : [ "%topology " <> from <> " -> {" <> T.intercalate ", " tos <> "}"
        | (from, tos) <- topTransitions
        ]

renderDataDecls :: [ChaseDataDecl] -> [Text]
renderDataDecls [] = []
renderDataDecls ds = concatMap one ds
  where
    one ChaseDataDecl{..} = [cddVerbatim, ""]

-- | Pattern synonyms render verbatim (combined sig + def if both
-- exist) followed by any invariants attached to the pattern name.
-- Same lookup mechanism as signatures: invariants reference the
-- pattern by its bare name.
renderPatternsWithInvariants :: [Pattern] -> [Invariant] -> [Text]
renderPatternsWithInvariants [] _ = []
renderPatternsWithInvariants pats invs =
  concatMap (renderPat invMap) pats
  where
    invMap = [(invFunction i, i) | i <- invs]
    renderPat m Pattern{..} =
      let attached = lookup patName m
          extra = case attached of
            Nothing -> []
            Just Invariant{..} ->
                 [ "  ! " <> l                | l <- invLines    ]
              <> [ "  > consumed by: " <> c   | c <- invConsumes ]
              <> case invBodyHint of
                   Nothing -> []
                   Just h  -> ["  " <> h]
      in [patVerbatim] <> extra <> [""]

-- | "!" lines are invariants. ">" lines are downstream consumers.
-- Both indented under the type sig.
renderSignaturesWithInvariants :: [Signature] -> [Invariant] -> [Text]
renderSignaturesWithInvariants sigs invs =
  concatMap (renderSig invMap) sigs
  where
    invMap = [(invFunction i, i) | i <- invs]
    renderSig m Signature{..} =
      let attached = lookup sigName m
          extra = case attached of
            Nothing -> []
            Just Invariant{..} ->
                 [ "  ! " <> l                | l <- invLines    ]
              <> [ "  > consumed by: " <> c   | c <- invConsumes ]
              <> case invBodyHint of
                   Nothing -> []
                   Just h  -> ["  " <> h]
      in [sigVerbatim] <> extra <> [""]

renderDecisions :: [Decision] -> [Text]
renderDecisions [] = []
renderDecisions ds = concatMap one ds
  where
    one Decision{..} =
      [ "%decision " <> decName
      , "  what:    " <> decWhat
      , "  why:     " <> decWhy
      , "  affects: " <> T.intercalate ", " decAffects
      , ""
      ]

renderParseErrors :: [Text] -> [Text]
renderParseErrors [] = []
renderParseErrors es = "" : [ "%parse_error " <> e | e <- es ]-- End of /home/bismuth/git/chase/src/Chase/Render.hs

-- Start of /home/bismuth/git/chase/src/Chase/Pipeline.hs
module Chase.Pipeline
  ( ChaseConfig (..)
  , defaultConfig
  , runChase
  , attachAnnotations
  , checkAnnotationDrift
  ) where

import qualified Data.Map.Strict as Map
import Data.Map.Strict (Map)
import qualified Data.Text as T
import Data.Text (Text)
import qualified Data.Text.IO as TIO
import Control.Monad (forM, forM_, when)
import Data.IORef (newIORef, modifyIORef', readIORef)
import Data.Time (getCurrentTime, defaultTimeLocale, formatTime)
import System.Directory
  ( createDirectoryIfMissing, doesDirectoryExist, listDirectory )
import System.FilePath
  ( (</>), (<.>), takeDirectory, takeExtension
  , dropExtension, makeRelative, equalFilePath
  )
import qualified Data.List

import Chase.Types
import Chase.Parse
import Chase.Render

data ChaseConfig = ChaseConfig
  { cfgSourceRoots :: [FilePath]
  , cfgOutputDir   :: FilePath
  , cfgBundleFile  :: Maybe FilePath
  , cfgAnnotations :: Map Text ModuleAnnotations
  , cfgVerbose     :: Bool
  }

defaultConfig :: ChaseConfig
defaultConfig = ChaseConfig
  { cfgSourceRoots = []
  , cfgOutputDir   = "chase"
  , cfgBundleFile  = Nothing
  , cfgAnnotations = Map.empty
  , cfgVerbose     = False
  }

runChase :: ChaseConfig -> IO ()
runChase cfg@ChaseConfig{..} = case cfgBundleFile of
  Nothing      -> runPerFile cfg
  Just bundle  -> runBundled cfg bundle

runPerFile :: ChaseConfig -> IO ()
runPerFile ChaseConfig{..} = do
  createDirectoryIfMissing True cfgOutputDir
  files <- concat <$> mapM findHaskellFiles cfgSourceRoots
  forM_ files \src -> do
    when cfgVerbose $ putStrLn $ "parse  " <> src
    result <- parseSourceFile src
    case result of
      Left ParseFailure{..} -> do
        putStrLn $ "WARN: parse failed for " <> pfPath
        TIO.putStrLn $ "  " <> pfMsg
      Right structural -> do
        let merged   = attachAnnotations cfgAnnotations structural
            outPath  = mkOutputPath cfgOutputDir cfgSourceRoots src
            rendered = renderChaseFile merged
            drift    = checkAnnotationDrift merged
        forM_ drift \w ->
          putStrLn $ "  drift: " <> T.unpack w
        createDirectoryIfMissing True (takeDirectory outPath)
        TIO.writeFile outPath rendered
        when cfgVerbose $ putStrLn $ "write  " <> outPath

runBundled :: ChaseConfig -> FilePath -> IO ()
runBundled ChaseConfig{..} bundlePath = do
  createDirectoryIfMissing True (takeDirectory bundlePath)
  files <- concat <$> mapM findHaskellFiles cfgSourceRoots
  failuresRef  <- newIORef (0 :: Int)
  successesRef <- newIORef (0 :: Int)
  blocks       <- forM files \src -> do
    when cfgVerbose $ putStrLn $ "parse  " <> src
    result <- parseSourceFile src
    case result of
      Left ParseFailure{..} -> do
        modifyIORef' failuresRef (+ 1)
        putStrLn $ "WARN: parse failed for " <> pfPath
        TIO.putStrLn $ "  " <> pfMsg
        pure (renderFailureBlock cfgSourceRoots src pfMsg)
      Right structural -> do
        modifyIORef' successesRef (+ 1)
        let merged   = attachAnnotations cfgAnnotations structural
            rendered = renderChaseFile merged
            drift    = checkAnnotationDrift merged
        forM_ drift \w ->
          putStrLn $ "  drift: " <> T.unpack w
        pure (renderBundleBlock cfgSourceRoots src rendered)

  successes <- readIORef successesRef
  failures  <- readIORef failuresRef
  preamble  <- renderPreamble cfgSourceRoots successes failures
  let bundle = preamble <> T.concat blocks
  TIO.writeFile bundlePath bundle
  when cfgVerbose $ do
    putStrLn $ "bundled " <> show successes
            <> " files (" <> show failures <> " parse failures)"
    putStrLn $ "write  " <> bundlePath

renderPreamble :: [FilePath] -> Int -> Int -> IO Text
renderPreamble roots ok failed = do
  now <- getCurrentTime
  let stamp = formatTime defaultTimeLocale "%Y-%m-%dT%H:%M:%SZ" now
  pure $ T.unlines
    [ "%bundle chase v1"
    , "%generated " <> T.pack stamp
    , "%roots " <> T.intercalate ", " (map T.pack roots)
    , "%files " <> T.pack (show ok) <> " ok, "
                <> T.pack (show failed) <> " failed"
    , ""
    , "# This file is a chase bundle: structural skeletons of multiple"
    , "# Haskell source files concatenated into one document. Each block"
    , "# begins with === BEGIN <path> === on its own line. Blocks contain"
    , "# the rendered .chase format: %file, %mod, %ext, %fixity, %uses,"
    , "# %const, %topology, data decls, %pattern, type signatures with"
    , "# attached invariants and consumers, %decision blocks, and parse"
    , "# errors. Function bodies are deliberately omitted; the lines"
    , "# beginning with ! after a signature are the behavioral facts you"
    , "# would otherwise have to infer from reading the source."
    , ""
    ]

renderBundleBlock :: [FilePath] -> FilePath -> Text -> Text
renderBundleBlock roots src rendered =
  let rel = relativeToRoots roots src
  in T.unlines
       [ ""
       , "=== BEGIN " <> T.pack rel <> " ==="
       , ""
       ] <> rendered

renderFailureBlock :: [FilePath] -> FilePath -> Text -> Text
renderFailureBlock roots src msg =
  let rel = relativeToRoots roots src
  in T.unlines
       [ ""
       , "=== BEGIN " <> T.pack rel <> " ==="
       , ""
       , "%parse_error " <> msg
       , ""
       ]

attachAnnotations
  :: Map Text ModuleAnnotations -> ChaseFile -> ChaseFile
attachAnnotations annMap cf =
  case Map.lookup (chaseModuleName cf) annMap of
    Nothing -> cf
    Just ModuleAnnotations{..} -> cf
      { chaseConstants  = annConstants
      , chaseInvariants = annInvariants
      , chaseDecisions  = annDecisions
      , chaseTopologies = annTopologies
      }

-- | Drift check: invariants and decision-affects names must point at
-- something the parser actually found. Valid targets are signatures
-- AND pattern synonyms (both can carry behavioral annotations).
-- Class/instance heads, data decls, and constants are NOT valid drift
-- targets here because invariants attach to functions and patterns
-- only.
checkAnnotationDrift :: ChaseFile -> [Text]
checkAnnotationDrift ChaseFile{..} =
  let validNames  = map sigName chaseSignatures
                 <> map patName chasePatterns
      invMissing  =
        [ "invariant references unknown function: " <> invFunction i
        | i <- chaseInvariants
        , invFunction i `notElem` validNames
        ]
      decMissing  =
        [ "decision " <> decName d
            <> " references unknown function: " <> n
        | d <- chaseDecisions
        , n <- decAffects d
        , n `notElem` validNames
        ]
  in invMissing <> decMissing

mkOutputPath :: FilePath -> [FilePath] -> FilePath -> FilePath
mkOutputPath outDir roots src =
  outDir </> dropExtension (relativeToRoots roots src) <.> "chase"

relativeToRoots :: [FilePath] -> FilePath -> FilePath
relativeToRoots roots src =
  let candidates =
        [ rel
        | root <- roots
        , let rel = makeRelative root src
        , not (equalFilePath rel src)
        ]
  in case candidates of
       (r:_) -> r
       []    -> src

findHaskellFiles :: FilePath -> IO [FilePath]
findHaskellFiles root = do
  exists <- doesDirectoryExist root
  if not exists
    then pure []
    else do
      entries <- Data.List.sort <$> listDirectory root
      let fullPaths = map (root </>) entries
      results <- forM fullPaths \p -> do
        isDir <- doesDirectoryExist p
        if isDir
          then findHaskellFiles p
          else pure [ p | takeExtension p == ".hs" ]
      pure (concat results)-- End of /home/bismuth/git/chase/src/Chase/Pipeline.hs

-- Start of /home/bismuth/git/chase/src/Chase/Types.hs
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}

module Chase.Types
  ( ChaseFile (..)
  , emptyChaseFile
  , Signature (..)
  , Pattern (..)
  , Fixity (..)
  , ChaseDataDecl (..)
  , ModuleAnnotations (..)
  , emptyAnnotations
  , Constant (..)
  , Note (..)
  , Invariant (..)
  , inv
  , invHinted
  , constNote
  , constBug
  , Decision (..)
  , decision
  , Topology (..)
  ) where

import Data.Text (Text)
import GHC.Generics (Generic)

-- | The canonical structural description of one Haskell source file as
-- chase sees it. Structural fields are populated by Chase.Parse;
-- annotation fields (constants, invariants, decisions, topologies) are
-- merged in later by Chase.Pipeline.attachAnnotations.
data ChaseFile = ChaseFile
  { chaseSourcePath  :: FilePath
  , chaseModuleName  :: Text
  , chaseExtensions  :: [Text]
  , chaseFixities    :: [Fixity]
  , chaseImports     :: [Text]
  , chaseSignatures  :: [Signature]
  , chasePatterns    :: [Pattern]
  , chaseDataDecls   :: [ChaseDataDecl]
  , chaseConstants   :: [Constant]
  , chaseInvariants  :: [Invariant]
  , chaseDecisions   :: [Decision]
  , chaseTopologies  :: [Topology]
  , chaseParseErrors :: [Text]
  }
  deriving stock (Show, Generic)

emptyChaseFile :: FilePath -> ChaseFile
emptyChaseFile path = ChaseFile
  { chaseSourcePath  = path
  , chaseModuleName  = ""
  , chaseExtensions  = []
  , chaseFixities    = []
  , chaseImports     = []
  , chaseSignatures  = []
  , chasePatterns    = []
  , chaseDataDecls   = []
  , chaseConstants   = []
  , chaseInvariants  = []
  , chaseDecisions   = []
  , chaseTopologies  = []
  , chaseParseErrors = []
  }

data Signature = Signature
  { sigName     :: Text
  , sigVerbatim :: Text
  , sigSrcLine  :: Int
  }
  deriving stock (Show, Generic)

-- | A pattern synonym, possibly with a separately-declared type
-- signature. patVerbatim is the rendered combined view: type sig (if
-- present) followed by definition.
data Pattern = Pattern
  { patName     :: Text
  , patVerbatim :: Text
  , patSrcLine  :: Int
  }
  deriving stock (Show, Generic)

-- | A top-level fixity declaration, e.g. 'infixr 5 :<>'. fixVerbatim
-- preserves the source as written. fixOps are the operator names this
-- declaration applies to (one fixity decl can name multiple ops).
data Fixity = Fixity
  { fixVerbatim :: Text
  , fixOps      :: [Text]
  , fixSrcLine  :: Int
  }
  deriving stock (Show, Generic)

data ChaseDataDecl = ChaseDataDecl
  { cddName     :: Text
  , cddVerbatim :: Text
  , cddSrcLine  :: Int
  }
  deriving stock (Show, Generic)

data ModuleAnnotations = ModuleAnnotations
  { annModName    :: Text
  , annConstants  :: [Constant]
  , annInvariants :: [Invariant]
  , annDecisions  :: [Decision]
  , annTopologies :: [Topology]
  }
  deriving stock (Show, Generic)

emptyAnnotations :: Text -> ModuleAnnotations
emptyAnnotations m = ModuleAnnotations m [] [] [] []

data Constant = Constant
  { constName     :: Text
  , constValueDoc :: Text
  , constNotes    :: [Note]
  }
  deriving stock (Show, Generic)

data Note = Note Text | BugNote Text
  deriving stock (Show, Generic)

constNote :: Text -> Note
constNote = Note

constBug :: Text -> Note
constBug = BugNote

data Invariant = Invariant
  { invFunction :: Text
  , invLines    :: [Text]
  , invConsumes :: [Text]
  , invBodyHint :: Maybe Text
  }
  deriving stock (Show, Generic)

inv :: Text -> [Text] -> Invariant
inv fn ls = Invariant fn ls [] Nothing

invHinted :: Text -> [Text] -> Text -> Invariant
invHinted fn ls hint = Invariant fn ls [] (Just hint)

data Decision = Decision
  { decName    :: Text
  , decWhat    :: Text
  , decWhy     :: Text
  , decAffects :: [Text]
  }
  deriving stock (Show, Generic)

decision :: Text -> Text -> Text -> [Text] -> Decision
decision = Decision

data Topology = Topology
  { topName        :: Text
  , topVertices    :: [Text]
  , topTransitions :: [(Text, [Text])]
  }
  deriving stock (Show, Generic)-- End of /home/bismuth/git/chase/src/Chase/Types.hs

-- Start of /home/bismuth/git/chase/src/Chase/Parse.hs
{-# LANGUAGE LambdaCase        #-}
{-# LANGUAGE OverloadedStrings #-}

module Chase.Parse
  ( parseSourceFile
  , ParseFailure (..)
  ) where

import qualified Data.Text          as T
import           Data.Text          (Text)
import qualified Data.Text.Encoding as TE
import qualified Data.ByteString    as BS
import           Data.List          (sortOn)
import qualified Data.Map.Strict    as Map

-- ghc-lib-parser
import GHC.Data.FastString       (mkFastString)
import GHC.Data.StringBuffer     (StringBuffer, stringToStringBuffer)
import qualified GHC.Settings    as Settings
import GHC.Settings.Config       (cProjectVersion)
import GHC.Platform              (genericPlatform, platformArchOS)
import GHC.Driver.Session        (DynFlags, defaultDynFlags, xopt_set, supportedLanguagesAndExtensions)
import GHC.Fingerprint           (fingerprint0)
import GHC.Unit.Types            (stringToUnitId)
import GHC.Driver.Config.Parser  (initParserOpts)
import qualified GHC.LanguageExtensions as LangExt
import GHC.Parser                (parseModule)
import GHC.Parser.Header         (getOptions)
import GHC.Parser.Lexer          (ParseResult (..), PState, initParserState, unP, getPsErrorMessages)
import GHC.Types.SrcLoc          (mkRealSrcLoc, unLoc, getLoc, SrcSpan (..),
                                  srcSpanStartLine, srcSpanEndLine)
import GHC.Hs                    (HsModule (..), GhcPs)
import GHC.Hs.Decls              (HsDecl (..), TyClDecl (..), InstDecl (..),
                                  ClsInstDecl (..), FamilyDecl (..), LHsDecl)
import GHC.Hs.Binds              (Sig (..), LSig, HsBindLR (..))
import GHC.Parser.Annotation     (locA)
import GHC.Types.Name.Reader     (RdrName, rdrNameOcc)
import GHC.Types.Name.Occurrence (occNameString)
import Language.Haskell.Syntax.Module.Name (moduleNameString)
import GHC.Utils.Outputable      (ppr, showSDocUnsafe)

import Chase.Types

------------------------------------------------------------------
-- Public API
------------------------------------------------------------------

data ParseFailure = ParseFailure
  { pfPath :: FilePath
  , pfMsg  :: Text
  }

parseSourceFile :: FilePath -> IO (Either ParseFailure ChaseFile)
parseSourceFile path = do
  bytes <- BS.readFile path
  let sourceText  = TE.decodeUtf8 bytes
      sourceLines = T.lines sourceText
      buf         = stringToStringBuffer (T.unpack sourceText)
      dflags      = applySourcePragmas path buf (defaultDynFlags probedSettings)
      pOpts       = initParserOpts dflags
      startLoc    = mkRealSrcLoc (mkFastString path) 1 1
      pstate0     = initParserState pOpts buf startLoc
  case unP parseModule pstate0 of
    POk _ locModule ->
      pure $ Right $ extractStructure path sourceText sourceLines (unLoc locModule)
    PFailed pst ->
      pure $ Left $ ParseFailure path (renderParseError pst)

------------------------------------------------------------------
-- LANGUAGE pragma application
------------------------------------------------------------------

applySourcePragmas :: FilePath -> StringBuffer -> DynFlags -> DynFlags
applySourcePragmas path buf df0 =
  let initialOpts       = initParserOpts df0
      (_warns, locOpts) = getOptions initialOpts (supportedLanguagesAndExtensions (platformArchOS genericPlatform)) buf path
      flagStrings       = map unLoc locOpts
  in foldl' applyOne df0 flagStrings
  where
    applyOne df flag =
      case parseExtensionFlag flag of
        Just LangExt.TemplateHaskell ->
          -- TemplateHaskell implies TemplateHaskellQuotes, which is what
          -- gates the `$` lexer rule. xopt_set does NOT walk extension
          -- implications, so we apply this one explicitly.
          xopt_set (xopt_set df LangExt.TemplateHaskell)
                   LangExt.TemplateHaskellQuotes
        Just ext -> xopt_set df ext
        Nothing  -> df

parseExtensionFlag :: String -> Maybe LangExt.Extension
parseExtensionFlag s = case s of
  '-':'X':rest -> readExtension rest
  _            -> Nothing
  where
    readExtension name =
      case [ ext | ext <- [minBound .. maxBound :: LangExt.Extension]
                 , show ext == name ] of
        (e:_) -> Just e
        []    -> Nothing

------------------------------------------------------------------
-- AST extraction
------------------------------------------------------------------

extractStructure
  :: FilePath -> Text -> [Text] -> HsModule GhcPs -> ChaseFile
extractStructure path sourceText sourceLines hsmod =
  (emptyChaseFile path)
    { chaseModuleName = moduleNameOf hsmod
    , chaseExtensions = pragmasFromSource sourceText
    , chaseFixities   = concatMap (extractFixity sourceLines) (hsmodDecls hsmod)
    , chaseImports    = importsOf hsmod
    , chaseSignatures = concatMap (extractSignatures sourceLines) (hsmodDecls hsmod)
    , chasePatterns   = mergePatterns
                          (concatMap (extractPatternSig  sourceLines) (hsmodDecls hsmod))
                          (concatMap (extractPatternBind sourceLines) (hsmodDecls hsmod))
    , chaseDataDecls  = concatMap (extractDataDecl  sourceLines) (hsmodDecls hsmod)
    }

renderParseError :: PState -> Text
renderParseError pst =
  let msgs = getPsErrorMessages pst
  in T.pack (showSDocUnsafe (ppr msgs))

moduleNameOf :: HsModule GhcPs -> Text
moduleNameOf m = case hsmodName m of
  Just lmn -> T.pack (moduleNameString (unLoc lmn))
  Nothing  -> ""

importsOf :: HsModule GhcPs -> [Text]
importsOf m = map renderImport (hsmodImports m)
  where
    renderImport limp = T.pack (showSDocUnsafe (ppr limp))

------------------------------------------------------------------
-- Signatures (top-level + class methods)
------------------------------------------------------------------

extractSignatures :: [Text] -> LHsDecl GhcPs -> [Signature]
extractSignatures sourceLines ldecl =
  let sp = locA (getLoc ldecl)
  in case unLoc ldecl of
       SigD _ sig -> sigToSignatures sourceLines sp sig
       TyClD _ (ClassDecl { tcdSigs = sigs }) ->
         concatMap (extractClassSig sourceLines) sigs
       _ -> []

extractClassSig :: [Text] -> LSig GhcPs -> [Signature]
extractClassSig sourceLines lsig =
  let sp = locA (getLoc lsig)
  in sigToSignatures sourceLines sp (unLoc lsig)

sigToSignatures :: [Text] -> SrcSpan -> Sig GhcPs -> [Signature]
sigToSignatures sourceLines sp = \case
  TypeSig _ names _ ->
    [ Signature (rdrNameToText (unLoc n))
                (sliceSourceSpan sourceLines sp)
                (startLine sp)
    | n <- names ]
  ClassOpSig _ _ names _ ->
    [ Signature (rdrNameToText (unLoc n))
                (sliceSourceSpan sourceLines sp)
                (startLine sp)
    | n <- names ]
  _ -> []

------------------------------------------------------------------
-- Pattern synonyms (definitions and signatures, merged by name)
------------------------------------------------------------------

-- | Extract pattern synonym TYPE SIGNATURES (PatSynSig). These can
-- appear separately from the pattern definition, e.g.:
--
--     pattern Foo :: Int -> Maybe Int
--     pattern Foo n = Just n
--
-- This function picks up only the signature line; extractPatternBind
-- picks up the definition; mergePatterns combines them.
extractPatternSig :: [Text] -> LHsDecl GhcPs -> [(Text, Int, Text)]
extractPatternSig sourceLines ldecl =
  let sp = locA (getLoc ldecl)
  in case unLoc ldecl of
       SigD _ (PatSynSig _ names _) ->
         [ ( rdrNameToText (unLoc n)
           , startLine sp
           , sliceSourceSpan sourceLines sp
           )
         | n <- names ]
       _ -> []

-- | Extract pattern synonym DEFINITIONS (PatSynBind inside a ValD).
-- We render the whole binding via the AST's pp instance and pull the
-- pattern name out of the rendered text. This dodges version-specific
-- field-name access on PatSynBind, which is a moving target.
extractPatternBind :: [Text] -> LHsDecl GhcPs -> [(Text, Int, Text)]
extractPatternBind sourceLines ldecl =
  let sp = locA (getLoc ldecl)
  in case unLoc ldecl of
       ValD _ bind -> case bind of
         PatSynBind _ _ ->
           let rendered = sliceSourceSpan sourceLines sp
               nm       = patternNameFromSource rendered
           in case nm of
                Just n  -> [(n, startLine sp, rendered)]
                Nothing -> []
         _ -> []
       _ -> []

-- | Pull the pattern name out of a rendered pattern synonym binding.
-- Handles three source shapes:
--   pattern Foo ...          -- alphabetic, prefix
--   pattern (:<<) ...        -- operator, parenthesized (always for sigs)
--   pattern x :<< xs = ...   -- operator, infix definition form
-- Returns the bare operator name without parentheses so the merge in
-- mergePatterns matches signatures to definitions.
patternNameFromSource :: Text -> Maybe Text
patternNameFromSource src =
  let trimmed = T.dropWhile isHSpace src
  in case T.stripPrefix "pattern" trimmed of
       Nothing -> Nothing
       Just rest ->
         let body = T.dropWhile isHSpace rest
         in case T.uncons body of
              -- Parenthesized operator: pattern (:<<) ...
              Just ('(', afterOpen) ->
                let opName = T.takeWhile (/= ')') afterOpen
                in if T.null opName then Nothing else Just (T.strip opName)
              -- Otherwise: alphabetic prefix OR infix-form definition
              _ ->
                let firstTok = T.takeWhile (\c -> not (isHSpace c)
                                                 && c /= '\n'
                                                 && c /= ',') body
                    rest'    = T.dropWhile isHSpace
                                 (T.dropWhile (\c -> not (isHSpace c)) body)
                    nextTok  = T.takeWhile (\c -> not (isHSpace c)
                                                 && c /= '\n') rest'
                in if isOperatorish nextTok && not (T.null nextTok)
                     -- pattern x :<< xs ... — middle token is the op
                     then Just nextTok
                     else if T.null firstTok
                       then Nothing
                       else Just firstTok
  where
    isHSpace c = c == ' ' || c == '\t'
    isOperatorish t =
         not (T.null t)
      && T.all isOpChar t
      && t `notElem` reservedSyntax
    isOpChar c = c `elem` (":!#$%&*+./<=>?@\\^|-~" :: [Char])
    -- Tokens made of operator characters that are reserved Haskell
    -- syntax, not pattern names. Without this filter, 'pattern Empty
    -- = []' would parse '=' as the operator and merge would break.
    reservedSyntax = ["=", "<-", "::", "->", "|", "@"]

-- | Merge pattern signatures (Map: name -> sig text + line) with
-- pattern definitions. If both exist, render combined; if only one
-- exists, render what we have.
mergePatterns
  :: [(Text, Int, Text)]  -- sigs
  -> [(Text, Int, Text)]  -- binds
  -> [Pattern]
mergePatterns sigs binds =
  let sigMap  = Map.fromList [ (n, (line, txt)) | (n, line, txt) <- sigs ]
      bindMap = Map.fromList [ (n, (line, txt)) | (n, line, txt) <- binds ]
      allNames = Map.keys (Map.union sigMap bindMap)
      build name =
        let mSig  = Map.lookup name sigMap
            mBind = Map.lookup name bindMap
            line = case (mSig, mBind) of
              (Just (l, _), _)       -> l
              (Nothing, Just (l, _)) -> l
              _                      -> 0
            verbatim = case (mSig, mBind) of
              (Just (_, s), Just (_, b)) -> s <> "\n" <> b
              (Just (_, s), Nothing)     -> s
              (Nothing, Just (_, b))     -> b
              _                          -> ""
        in Pattern name verbatim line
  in sortOn patSrcLine (map build allNames)

------------------------------------------------------------------
-- Fixity declarations
------------------------------------------------------------------

extractFixity :: [Text] -> LHsDecl GhcPs -> [Fixity]
extractFixity sourceLines ldecl =
  let sp = locA (getLoc ldecl)
  in case unLoc ldecl of
       SigD _ (FixSig _ _) ->
         let verbatim = sliceSourceSpan sourceLines sp
         in [ Fixity verbatim (fixityOpsFromSource verbatim) (startLine sp) ]
       _ -> []

-- | Parse 'infixr 5 <>, :<>, :|>' style declarations. We strip the
-- direction keyword and precedence, then split the rest on commas.
fixityOpsFromSource :: Text -> [Text]
fixityOpsFromSource src =
  let trimmed = T.strip src
      afterKw = case asum [ T.stripPrefix kw trimmed | kw <- ["infixr", "infixl", "infix"] ] of
        Just rest -> T.stripStart rest
        Nothing   -> trimmed
      afterPrec = T.dropWhile (\c -> c == ' ' || (c >= '0' && c <= '9'))
                              (T.dropWhile (== ' ') afterKw)
      ops = T.splitOn "," afterPrec
  in filter (not . T.null) (map T.strip ops)
  where
    asum []     = Nothing
    asum (x:xs) = case x of
      Just _  -> x
      Nothing -> asum xs

------------------------------------------------------------------
-- Data, newtype, type, class, instance, type/data family
------------------------------------------------------------------

extractDataDecl :: [Text] -> LHsDecl GhcPs -> [ChaseDataDecl]
extractDataDecl sourceLines ldecl =
  let sp = locA (getLoc ldecl)
  in case unLoc ldecl of
       TyClD _ tcd -> case tcd of
         DataDecl  { tcdLName = n } -> [mkFull sp n]
         SynDecl   { tcdLName = n } -> [mkFull sp n]
         ClassDecl { tcdLName = n } -> [mkHeadOnly sp n]
         FamDecl _ (FamilyDecl { fdLName = n }) -> [mkFull sp n]
       InstD _ (ClsInstD _ (ClsInstDecl { cid_poly_ty = lty })) ->
         [ ChaseDataDecl
             (T.pack (showSDocUnsafe (ppr lty)))
             (sliceFirstLine sourceLines sp)
             (startLine sp)
         ]
       _ -> []
  where
    mkFull sp lname = ChaseDataDecl
      (rdrNameToText (unLoc lname))
      (sliceSourceSpan sourceLines sp)
      (startLine sp)
    mkHeadOnly sp lname = ChaseDataDecl
      (rdrNameToText (unLoc lname))
      (sliceFirstLine sourceLines sp)
      (startLine sp)

------------------------------------------------------------------
-- Names and source-span slicing
------------------------------------------------------------------

rdrNameToText :: RdrName -> Text
rdrNameToText = T.pack . occNameString . rdrNameOcc

startLine :: SrcSpan -> Int
startLine = \case
  RealSrcSpan rss _ -> srcSpanStartLine rss
  UnhelpfulSpan _   -> 0

sliceSourceSpan :: [Text] -> SrcSpan -> Text
sliceSourceSpan ls = \case
  RealSrcSpan rss _ ->
    let s = srcSpanStartLine rss
        e = srcSpanEndLine   rss
    in T.intercalate "\n" $ take (e - s + 1) $ drop (s - 1) ls
  UnhelpfulSpan _ -> ""

sliceFirstLine :: [Text] -> SrcSpan -> Text
sliceFirstLine ls = \case
  RealSrcSpan rss _ ->
    let s = srcSpanStartLine rss
    in case drop (s - 1) ls of
         (line:_) -> line
         []       -> ""
  UnhelpfulSpan _ -> ""

------------------------------------------------------------------
-- LANGUAGE pragma extraction (textual; for chase output only)
------------------------------------------------------------------

pragmasFromSource :: Text -> [Text]
pragmasFromSource src =
  [ T.strip ext
  | line <- takeWhile isPreambleLine (T.lines src)
  , Just rest <- [T.stripPrefix "{-#" (T.strip line)]
  , Just exts <- [extractLanguagePragma rest]
  , ext <- T.splitOn "," exts
  ]
  where
    isPreambleLine line =
      let s = T.strip line
      in T.null s
      || "--" `T.isPrefixOf` s
      || "{-" `T.isPrefixOf` s
      || "#"  `T.isPrefixOf` s
    extractLanguagePragma rest =
      let s = T.strip rest
      in case T.stripPrefix "LANGUAGE" s of
           Just body ->
             let body' = T.strip body
                 stripped = case T.stripSuffix "#-}" body' of
                   Just b  -> T.strip b
                   Nothing -> body'
             in Just stripped
           Nothing -> Nothing

------------------------------------------------------------------
-- DynFlags / Settings placeholder construction
------------------------------------------------------------------

probedSettings :: Settings.Settings
probedSettings = Settings.Settings
  { Settings.sGhcNameVersion = probedGhcNameVersion
  , Settings.sFileSettings   = probedFileSettings
  , Settings.sTargetPlatform = genericPlatform
  , Settings.sToolSettings   = probedToolSettings
  , Settings.sPlatformMisc   = probedPlatformMisc
  , Settings.sRawSettings    = []
  , Settings.sUnitSettings   = probedUnitSettings
  }

probedGhcNameVersion :: Settings.GhcNameVersion
probedGhcNameVersion = Settings.GhcNameVersion
  { Settings.ghcNameVersion_programName    = "ghc"
  , Settings.ghcNameVersion_projectVersion = cProjectVersion
  }

probedFileSettings :: Settings.FileSettings
probedFileSettings = Settings.FileSettings
  { Settings.fileSettings_ghcUsagePath          = ""
  , Settings.fileSettings_ghciUsagePath         = ""
  , Settings.fileSettings_topDir                = ""
  , Settings.fileSettings_toolDir               = Nothing
  , Settings.fileSettings_globalPackageDatabase = ""
  }

probedPlatformMisc :: Settings.PlatformMisc
probedPlatformMisc = Settings.PlatformMisc
  { Settings.platformMisc_targetPlatformString               = ""
  , Settings.platformMisc_ghcWithInterpreter                 = False
  , Settings.platformMisc_libFFI                             = False
  , Settings.platformMisc_llvmTarget                         = ""
  , Settings.platformMisc_targetRTSLinkerOnlySupportsSharedLibs = False
  }

probedUnitSettings :: Settings.UnitSettings
probedUnitSettings = Settings.UnitSettings
  { Settings.unitSettings_baseUnitId = stringToUnitId "base"
  }

probedToolSettings :: Settings.ToolSettings
probedToolSettings = Settings.ToolSettings
  { Settings.toolSettings_ldSupportsCompactUnwind        = False
  , Settings.toolSettings_ldSupportsFilelist             = False
  , Settings.toolSettings_ldSupportsSingleModule         = False
  , Settings.toolSettings_mergeObjsSupportsResponseFiles = False
  , Settings.toolSettings_ldIsGnuLd                      = False
  , Settings.toolSettings_ccSupportsNoPie                = False
  , Settings.toolSettings_useInplaceMinGW                = False
  , Settings.toolSettings_arSupportsDashL                = False
  , Settings.toolSettings_cmmCppSupportsG0               = False
  , Settings.toolSettings_pgm_L                          = ""
  , Settings.toolSettings_pgm_P                          = ("", [])
  , Settings.toolSettings_pgm_JSP                        = ("", [])
  , Settings.toolSettings_pgm_CmmP                       = ("", [])
  , Settings.toolSettings_pgm_F                          = ""
  , Settings.toolSettings_pgm_c                          = ""
  , Settings.toolSettings_pgm_cxx                        = ""
  , Settings.toolSettings_pgm_cpp                        = ("", [])
  , Settings.toolSettings_pgm_a                          = ("", [])
  , Settings.toolSettings_pgm_l                          = ("", [])
  , Settings.toolSettings_pgm_lm                         = Nothing
  , Settings.toolSettings_pgm_windres                    = ""
  , Settings.toolSettings_pgm_ar                         = ""
  , Settings.toolSettings_pgm_otool                      = ""
  , Settings.toolSettings_pgm_install_name_tool          = ""
  , Settings.toolSettings_pgm_ranlib                     = ""
  , Settings.toolSettings_pgm_lo                         = ("", [])
  , Settings.toolSettings_pgm_lc                         = ("", [])
  , Settings.toolSettings_pgm_las                        = ("", [])
  , Settings.toolSettings_pgm_i                          = ""
  , Settings.toolSettings_opt_L                          = []
  , Settings.toolSettings_opt_P                          = []
  , Settings.toolSettings_opt_JSP                        = []
  , Settings.toolSettings_opt_CmmP                       = []
  , Settings.toolSettings_opt_P_fingerprint              = fingerprint0
  , Settings.toolSettings_opt_JSP_fingerprint            = fingerprint0
  , Settings.toolSettings_opt_CmmP_fingerprint           = fingerprint0
  , Settings.toolSettings_opt_F                          = []
  , Settings.toolSettings_opt_c                          = []
  , Settings.toolSettings_opt_cxx                        = []
  , Settings.toolSettings_opt_a                          = []
  , Settings.toolSettings_opt_l                          = []
  , Settings.toolSettings_opt_lm                         = []
  , Settings.toolSettings_opt_windres                    = []
  , Settings.toolSettings_opt_lo                         = []
  , Settings.toolSettings_opt_lc                         = []
  , Settings.toolSettings_opt_las                        = []
  , Settings.toolSettings_opt_i                          = []
  , Settings.toolSettings_extraGccViaCFlags              = []
  }-- End of /home/bismuth/git/chase/src/Chase/Parse.hs

-- Start of /home/bismuth/git/chase/src/Chase/Annotations/Json.hs
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}

-- | Load 'ModuleAnnotations' from a single JSON file. The shape:
--
-- > {
-- >   "version": 1,
-- >   "modules": {
-- >     "DB.Auth": {
-- >       "decisions": [
-- >         { "name": "...", "what": "...",
-- >           "why": "..." | ["...","..."],
-- >           "affects": ["fn1", "fn2"] }
-- >       ],
-- >       "invariants": {
-- >         "hashPassword": ["line one", "line two"],
-- >         "createSession": {
-- >           "intent": "...",
-- >           "effects": ["DBPool", "IO"],
-- >           "notes":  ["..."],
-- >           "spec":   [{"input": "...", "expected": "..."}],
-- >           "consumes": ["Server.Auth.loginHandler", "..."],
-- >           "hint":   "body: ~30 lines, see source"
-- >         }
-- >       },
-- >       "constants": [
-- >         { "name": "...", "value": "...",
-- >           "notes": ["plain note", "BUG: bug note"] }
-- >       ],
-- >       "topologies": [
-- >         { "name": "...", "vertices": ["A","B"],
-- >           "transitions": { "A": ["B"], "B": ["A"] } }
-- >       ]
-- >     }
-- >   }
-- > }
module Chase.Annotations.Json
  ( loadAnnotations
  , loadAnnotationsIfExists
  ) where

import qualified Data.Aeson as A
import qualified Data.Aeson.Key as Key
import qualified Data.Aeson.KeyMap as KM
import qualified Data.Aeson.Types as AT
import qualified Data.ByteString.Lazy as LBS
import qualified Data.Map.Strict as Map
import Data.Map.Strict (Map)
import qualified Data.Text as T
import Data.Text (Text)
import System.Directory (doesFileExist)

import Chase.Types

-- | Load annotations from a JSON file. Returns Left if the file is
-- missing or fails to parse, with a message suitable for stderr.
loadAnnotations
  :: FilePath -> IO (Either String (Map Text ModuleAnnotations))
loadAnnotations path = do
  exists <- doesFileExist path
  if not exists
    then pure $ Left $ "annotations file not found: " <> path
    else do
      bs <- LBS.readFile path
      pure $ case A.eitherDecode bs of
        Left  e -> Left  $ path <> ": " <> e
        Right v -> case AT.parse parseRoot v of
          AT.Error   e -> Left  $ path <> ": " <> e
          AT.Success m -> Right m

-- | If the file exists and parses, return its contents.
-- If missing, return empty silently. Parse errors are also silenced
-- here — use 'loadAnnotations' if you want to surface them.
loadAnnotationsIfExists :: FilePath -> IO (Map Text ModuleAnnotations)
loadAnnotationsIfExists path = do
  exists <- doesFileExist path
  if not exists
    then pure Map.empty
    else either (const Map.empty) id <$> loadAnnotations path

-- top level ------------------------------------------------------------

parseRoot :: A.Value -> AT.Parser (Map Text ModuleAnnotations)
parseRoot = A.withObject "AnnotationsFile" $ \o -> do
  ver <- o A..:? "version" A..!= (1 :: Int)
  if ver /= 1
    then fail $ "unsupported annotations version: " <> show ver
    else (o A..: "modules") >>= parseModulesMap

parseModulesMap :: A.Object -> AT.Parser (Map Text ModuleAnnotations)
parseModulesMap obj =
  Map.fromList <$> mapM parsePair (KM.toList obj)
  where
    parsePair (k, v) = do
      let modName = Key.toText k
      ann <- parseModule modName v
      pure (modName, ann)

parseModule :: Text -> A.Value -> AT.Parser ModuleAnnotations
parseModule modName =
  A.withObject ("module " <> T.unpack modName) $ \o -> do
    consts  <- o A..:? "constants"  A..!= []
    invsObj <- o A..:? "invariants" A..!= KM.empty
    decs    <- o A..:? "decisions"  A..!= []
    tops    <- o A..:? "topologies" A..!= []
    pConsts <- mapM parseConstant consts
    pInvs   <- parseInvariantsMap invsObj
    pDecs   <- mapM parseDecision decs
    pTops   <- mapM parseTopology tops
    pure ModuleAnnotations
      { annModName    = modName
      , annConstants  = pConsts
      , annInvariants = pInvs
      , annDecisions  = pDecs
      , annTopologies = pTops
      }

-- constants ------------------------------------------------------------

parseConstant :: A.Value -> AT.Parser Constant
parseConstant = A.withObject "constant" $ \o -> do
  name  <- o A..:  "name"
  value <- o A..:  "value"
  notes <- o A..:? "notes" A..!= []
  pure Constant
    { constName     = name
    , constValueDoc = value
    , constNotes    = map noteFromText notes
    }

noteFromText :: Text -> Note
noteFromText t = case T.stripPrefix "BUG: " t of
  Just rest -> BugNote rest
  Nothing   -> Note t

-- invariants -----------------------------------------------------------

-- | Each invariant value is either:
--
--   * an array of strings (the @!@ lines verbatim, no consumes), or
--   * an object with optional fields @intent@, @effects@, @notes@,
--     @spec@, @consumes@, @hint@.
parseInvariantsMap :: A.Object -> AT.Parser [Invariant]
parseInvariantsMap obj = mapM parseOne (KM.toList obj)
  where
    parseOne (k, v) = parseInvariantValue (Key.toText k) v

parseInvariantValue :: Text -> A.Value -> AT.Parser Invariant
parseInvariantValue fnName = \case
  v@(A.Array _) -> inv fnName <$> AT.parseJSON v
  A.Object o    -> parseObjectInvariant fnName o
  _             -> fail $ "invariants." <> T.unpack fnName
                   <> " must be an array of strings or an object"

parseObjectInvariant :: Text -> A.Object -> AT.Parser Invariant
parseObjectInvariant fnName o = do
  mIntent  <- o A..:? "intent"
  effects  <- o A..:? "effects"  A..!= ([] :: [Text])
  notes    <- o A..:? "notes"    A..!= ([] :: [Text])
  specs    <- o A..:? "spec"     A..!= ([] :: [SpecEntry])
  consumes <- o A..:? "consumes" A..!= ([] :: [Text])
  hint     <- o A..:? "hint"
  let intentLine = maybe [] (\t -> ["intent: " <> t]) mIntent
      effectLine =
        if null effects
          then []
          else ["effects: " <> T.intercalate ", " effects]
      lns = intentLine <> effectLine <> notes <> map renderSpec specs
  pure $ Invariant fnName lns consumes hint

data SpecEntry = SpecEntry
  { seInput    :: Text
  , seExpected :: Text
  }

instance A.FromJSON SpecEntry where
  parseJSON = A.withObject "spec" $ \o -> SpecEntry
    <$> o A..: "input"
    <*> o A..: "expected"

renderSpec :: SpecEntry -> Text
renderSpec SpecEntry{..} = "spec: " <> seInput <> " => " <> seExpected

-- decisions ------------------------------------------------------------

parseDecision :: A.Value -> AT.Parser Decision
parseDecision = A.withObject "decision" $ \o -> do
  name    <- o A..:  "name"
  what    <- o A..:  "what"
  whyVal  <- o A..:? "why" A..!= A.String ""
  affects <- o A..:? "affects" A..!= []
  why <- case whyVal of
    A.String s    -> pure s
    a@(A.Array _) -> T.intercalate " " <$> AT.parseJSON a
    _ -> fail "decision.why must be a string or array of strings"
  pure $ Decision name what why affects

-- topologies -----------------------------------------------------------

parseTopology :: A.Value -> AT.Parser Topology
parseTopology = A.withObject "topology" $ \o -> do
  name     <- o A..: "name"
  vertices <- o A..: "vertices"
  transObj <- o A..: "transitions"
  trans    <- mapM parseTransPair (KM.toList transObj)
  pure Topology
    { topName        = name
    , topVertices    = vertices
    , topTransitions = trans
    }
  where
    parseTransPair (k, v) = do
      tos <- AT.parseJSON v
      pure (Key.toText k, tos)-- End of /home/bismuth/git/chase/src/Chase/Annotations/Json.hs

-- Start of /home/bismuth/git/chase/app/Main.hs
{-# LANGUAGE LambdaCase #-}

module Main (main) where

import qualified Data.Map.Strict as Map
import Data.Map.Strict (Map)
import Data.List (isSuffixOf)
import Data.Text (Text)
import System.Directory (doesFileExist)
import System.Environment (getArgs, getProgName)
import System.Exit (exitFailure)
import System.IO (hPutStrLn, stderr)

import Chase

defaultAnnotationsPath :: FilePath
defaultAnnotationsPath = "chase-annotations.json"

main :: IO ()
main = do
  args <- getArgs
  prog <- getProgName
  case args of
    [src, out]               -> runWith src out Nothing
    [src, out, annPath]      -> runWith src out (Just annPath)
    _                         -> usage prog

runWith :: FilePath -> FilePath -> Maybe FilePath -> IO ()
runWith src out mExplicit = do
  annPath <- resolveAnnotationsPath mExplicit
  anns    <- loadAnnotationsOrDie annPath
  let bundleMode = ".chase" `isSuffixOf` out
      cfg | bundleMode = defaultConfig
              { cfgSourceRoots = [src]
              , cfgBundleFile  = Just out
              , cfgAnnotations = anns
              , cfgVerbose     = True
              }
          | otherwise = defaultConfig
              { cfgSourceRoots = [src]
              , cfgOutputDir   = out
              , cfgAnnotations = anns
              , cfgVerbose     = True
              }
  runChase cfg

-- | If the user gave an explicit path, use it (must exist).
-- Otherwise look for ./chase-annotations.json. Missing default is fine
-- (silent empty annotations); missing explicit is a user error.
resolveAnnotationsPath :: Maybe FilePath -> IO (Maybe FilePath)
resolveAnnotationsPath = \case
  Just p -> do
    exists <- doesFileExist p
    if exists
      then pure (Just p)
      else do
        hPutStrLn stderr $ "error: annotations file not found: " <> p
        exitFailure
  Nothing -> do
    exists <- doesFileExist defaultAnnotationsPath
    pure $ if exists then Just defaultAnnotationsPath else Nothing

loadAnnotationsOrDie
  :: Maybe FilePath -> IO (Map Text ModuleAnnotations)
loadAnnotationsOrDie Nothing = pure Map.empty
loadAnnotationsOrDie (Just p) = do
  result <- loadAnnotations p
  case result of
    Right m -> do
      putStrLn $ "load   " <> p <> " (" <> show (Map.size m) <> " modules)"
      pure m
    Left e -> do
      hPutStrLn stderr $ "error: " <> e
      exitFailure

usage :: String -> IO ()
usage prog = do
  hPutStrLn stderr $ "error: expected 2 or 3 arguments"
  hPutStrLn stderr ""
  mapM_ (hPutStrLn stderr)
    [ "usage: " <> prog <> " <source-root> <output> [<annotations.json>]"
    , ""
    , "  source-root        directory to walk for .hs files"
    , "  output             if it ends in .chase, written as a single"
    , "                     concatenated bundle file; otherwise treated"
    , "                     as a directory for per-file .chase output"
    , "  annotations.json   optional path to annotations JSON file."
    , "                     If omitted, ./chase-annotations.json is used"
    , "                     when present. If the explicit path is given"
    , "                     and missing, this is a hard error."
    , ""
    , "examples:"
    , "  " <> prog <> " backend/src cheeblr.chase"
    , "  " <> prog <> " backend/src cheeblr.chase ./chase-annotations.json"
    ]
  exitFailure-- End of /home/bismuth/git/chase/app/Main.hs

